name: 'esquio-rollout-v3'
description: 'Xabaril Esquio Rollout task (V3)'
author: 'Xabaril'
branding:
  icon: 'toggle-right'  
  color: 'blue'
inputs:
  esquio-url:             
    description: 'Esquio URL'
    required: true
  esquio-api-key:
    description: 'Esquio API KEy (keep it secret)'
    required: true
  product-name:
    description: 'Product name'
    required: true
  feature-name:
    description: 'Feature name'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
